import Wrapper from '@/Components/Wrapper'
import './globals.css'
import { WrapperContext } from '@/context/WrapperContext/WrapperContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className=''>
        <WrapperContext>
          <Wrapper> {children}</Wrapper>
        </WrapperContext>
      </body>
    </html>
  )
}
